### ISSUE TITLE
Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by ixam1** [OlivierChirouze/schema-to-types#1]
Hi thanks for this useful package, but I cant use it properly unfortunately.

I get the following error:

```
TypeError: Cannot read property 'getPath' of undefined
    at getPath (C:\DEV\meteor\my-app\node_modules\ts-morph\dist\ts-morph.js:17688:108)
    at Directory.getRelativePathTo (C:\DEV\meteor\my-app\node_modules\ts-morph\dist\ts-morph.js:17686:67)
    at SourceFile.getRelativePathTo (C:\DEV\meteor\my-app\node_modules\ts-morph\dist\ts-morph.js:12905:36)
    at C:\DEV\meteor\my-app\node_modules\schema-to-types\dist\src\schema-import.js:49:22
    at Array.map (<anonymous>)
    at SchemaImport.generateModel (C:\DEV\meteor\my-app\node_modules\schema-to-types\dist\src\schema-import.js:42:14)
    at Object.<anonymous> (C:\DEV\meteor\my-app\node_modules\schema-to-types\dist\src\update-model.js:8:89)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

It has something to do with these lines: 
https://github.com/OlivierChirouze/schema-to-types/blob/03212ea1d9eb7f92fc66acec87f183d14f9b6ff6/src/schema-import.ts#L58-L76

`d.getModuleSpecifierSourceFile()` returns undefined

I tried digging a bit myself, but got stuck. Do you have any idea why this might be happening?

**Comment by OlivierChirouze** [comment]
Hi!

Happy if this little library can be useful to someone else ;-)
Apparently what happens is one of the imported module in your file cannot be resolved.

Would you mind share the file you are trying to "convert", or at least the first lines when you import other modules?
I suspect one of these imports is "special" and I don't handle this case correctly. If I can reproduce it locally with an extract of your file, that would probably help.

Thanks

**Comment by ixam1** [comment]
And I am happy to have found it ;)

I found the culprit, its because of this: `import { defaultMeta } from "../simpleSchema"`

```
import SimpleSchema from "simpl-schema"
import { defaultMeta } from "../simpleSchema"
import { SchemaMap } from "schema-to-types"

export const userAdditionalFields = new SimpleSchema({
	field1: {
		type: String,
	},
	field2: {
		type: String,
	},
	...defaultMeta,
})

export const schemas: SchemaMap = {
	user: userAdditionalFields,
}
```

When i removed `defaultMeta` it worked. It would be awesome if you could fix this :)

**Comment by OlivierChirouze** [comment]
I tried to reproduce this (using a relative path to a file that is in the parent dir), but it worked. (see this branch: https://github.com/OlivierChirouze/schema-to-types/commit/ec5b9285b103703323e089b7195a04a5940276b8)
The method that you identified, that returns `undefined`, comes from [ts-morph](https://ts-morph.com/details/imports).

However it's hard to understand in which case it will return `undefined`, except if the "import file is not found".

So I'm wondering if the issue is not that the referenced file (in your case, must be something like "../simpleSchema.ts" is:
- outside of the tsconfig.ts included files
- with a different case (sometimes on MacOs, files are case insensitive, sometimes they are case sensitive...)

I'd really need to reproduce the issue to play around.

Would you be able to share the code or at least part of it?

Thanks

**Comment by ixam1** [comment]
> outside of the tsconfig.ts included files

Aaah I got it now. As I am gradually moving parts of my app to typescript the file in question was a .js file not .ts

I changed the file and now its working. 

So you can only import typescript files, maybe add a quick note in the readme. A typescript scrub like me didnt know this. 

I hope you didnt spend to much time reproducing, thanks a lot! :)

**Comment by OlivierChirouze** [comment]
Well, I think now v1.1.0 it supports it :-D

https://www.npmjs.com/package/schema-to-types

Thanks for your feedback!

**Comment by ixam1** [comment]
> Well, I think now v1.1.0 it supports it :-D
> 
> https://www.npmjs.com/package/schema-to-types

Nice, even better!
